name: CD - 部署Recat前端

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - frontend/react/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        #工作目录
        working-directory: ./frontend/react
    steps:
      #checkout main分支
      - uses: actions/checkout@v3
      - name: 设置版本号
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          chmod +x ../../.ci/build-publish.sh
          USERNAME=kobe4cn \
          REPO=spring3-react \
          TAG=${{ steps.build-number.outputs.BUILD_NUMBER }} \
          ../../.ci/build-publish.sh . \
            --build-arg api_base_url=
      - name: 更新Dockerrun.aws.json文件中的image拉取版本号
        run: |
          echo "更新Dockerrun.aws.json 前"
          cat ../../Dockerrun.aws.json
          echo "开始更新dockerrun文件"
          sed -i -E 's_(kobe4cn/spring3-react:)([^"]*)_\1'${{steps.build-number.outputs.BUILD_NUMBER}}'_' ../../Dockerrun.aws.json
          echo "更新完dockerrun文件"
          cat ../../Dockerrun.aws.json
      - name: 部署Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.SHA }}
          region: ${{ secrets.EB_REGION }}
          deployment_package: Dockerrun.aws.json
          wait_for_environment_recovery: 60
      - name: 提交Dockerrun.aws.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ../../Dockerrun.aws.json
          git commit -m "更新 Dockerrun.aws.json docker image tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push